trigger:
  branches:
    include:
      - master

variables:
  - template: pipeline-vars.yml

  - name: imageName
    value: '${{variables.teamName}}/${{variables.applicationName}}'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPush
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '${{variables.containerRegistryServiceConnection}}'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags:
          $(Build.BuildId)

# - stage: Deploy
#   displayName: 'Deploy to Azure Web App'
#   dependsOn: Build
#   condition: succeeded()
#   jobs:
#   - job: Deploy
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: AzureWebAppContainer@1
#       inputs:
#         azureSubscription: '$(azureSubscriptionServiceConnection)'
#         appName: '${{variables.webAppName}}'
#         containers: '${{lower(variables.containerRegistryServiceConnection)}}.azurecr.io/$(imageName):$(Build.BuildId)'